import { Database } from './db';
import { DbTypeOverrides } from './overrides';

/**
 * Utility type to apply column type overrides to a base type.
 * Replaces (rather than intersects) column types with any overrides defined in DbTypeOverrides.
 */
export type ApplyOverrides<
	Schema extends 'data' | 'users',
	Type extends 'Views' | 'Tables',
	T extends keyof Database[Schema][Type]
> = Database[Schema][Type][T] extends { Row: infer R }
	? T extends keyof DbTypeOverrides[Schema][Type]
		? DbTypeOverrides[Schema][Type][T] extends Record<string, any>
			? Omit<R, keyof DbTypeOverrides[Schema][Type][T]> & DbTypeOverrides[Schema][Type][T]
			: R
		: R
	: never;

/**
 * Utility type to apply overrides to a table/view definition.
 * Preserves Insert, Update, and Relationships while overriding Row.
 */
type ApplyTableOverrides<
	Schema extends 'data' | 'users',
	Type extends 'Views' | 'Tables',
	T extends keyof Database[Schema][Type]
> = Database[Schema][Type][T] extends infer Original
	? Original extends { Row: any }
		? Omit<Original, 'Row'> & {
				Row: ApplyOverrides<Schema, Type, T>;
		  }
		: Original
	: never;

/**
 * Utility type to apply return type overrides to a function definition.
 * Only overrides Returns (Args are left exactly as generated by Supabase).
 */
type ApplyFunctionOverrides<
	Schema extends 'data' | 'users',
	T extends keyof Database[Schema]['Functions']
> = Database[Schema]['Functions'][T] extends infer Original
	? Original extends { Returns: any; Args: any }
		? Omit<Original, 'Returns'> & {
				Returns: T extends keyof DbTypeOverrides[Schema]['Functions']
					? DbTypeOverrides[Schema]['Functions'][T]
					: Original['Returns'];
		  }
		: Original
	: never;

/**
 * Database type with overrides applied.
 * Use this type when creating Supabase clients to get automatic type overrides.
 */
export type DatabaseWithOverrides = Omit<Database, 'data' | 'users'> & {
	data: Omit<Database['data'], 'Tables' | 'Views' | 'Functions'> & {
		Tables: {
			[K in keyof Database['data']['Tables']]: ApplyTableOverrides<'data', 'Tables', K>;
		};
		Views: {
			[K in keyof Database['data']['Views']]: ApplyTableOverrides<'data', 'Views', K>;
		};
		Functions: {
			[K in keyof Database['data']['Functions']]: ApplyFunctionOverrides<'data', K>;
		};
	};
	users: Omit<Database['users'], 'Tables' | 'Views' | 'Functions'> & {
		Tables: {
			[K in keyof Database['users']['Tables']]: ApplyTableOverrides<'users', 'Tables', K>;
		};
		Views: {
			[K in keyof Database['users']['Views']]: ApplyTableOverrides<'users', 'Views', K>;
		};
		Functions: {
			[K in keyof Database['users']['Functions']]: ApplyFunctionOverrides<'users', K>;
		};
	};
};
